[package]
name = "limiter"
version = "0.2.1"
authors = ["Garrett Squire <garrettsquire@gmail.com>"]
description = "Request size limiting for the Iron framework"
repository = "https://github.com/gsquire/limiter"
keywords = ["iron", "http", "hyper"]
license = "MIT"

[dependencies]
iron = "0.4"
